USE wokilite;

CREATE TABLE IF NOT EXISTS customers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    email VARCHAR(255) UNIQUE,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS restaurants (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    timezone VARCHAR(100) NOT NULL,
    shifts JSON,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sector (
    id VARCHAR(50) PRIMARY KEY,
    restaurantId VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_sector_restaurant FOREIGN KEY (restaurantId) REFERENCES restaurants(id)
);

CREATE TABLE IF NOT EXISTS tables (
    id VARCHAR(50) PRIMARY KEY,
    sectorId CHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    minSize INT NOT NULL,
    maxSize INT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_table_sector FOREIGN KEY (sectorId) REFERENCES sector(id)
);

CREATE TABLE IF NOT EXISTS reservations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    restaurantId VARCHAR(50) NOT NULL,
    sectorId VARCHAR(50) NOT NULL,
    tableId VARCHAR(50) NOT NULL,
    customerId INT NOT NULL,
    partySize INT NOT NULL,
    startDateTimeISO DATETIME NOT NULL,
    endDateTimeISO DATETIME NOT NULL,
    status ENUM('PENDING', 'CONFIRMED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
    notes TEXT,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_reservation_restaurant FOREIGN KEY (restaurantId) REFERENCES restaurants(id),
    CONSTRAINT fk_reservation_sector FOREIGN KEY (sectorId) REFERENCES sector(id),
    CONSTRAINT fk_reservation_table FOREIGN KEY (tableId) REFERENCES tables(id),
    CONSTRAINT fk_reservation_customer FOREIGN KEY (customerId) REFERENCES customers(id)
);